// GENERISANO iz naselja-srbije.ts — ne uređivati ručno pojedinačna naselja.
// Mapiranje naselje → opština (prvo pojavljivanje u izvornom spisku) +
// približne koordinate CENTRA OPŠTINE (~km tačnost). Udaljenosti na Pijaci
// se računaju između centara opština — dovoljno za filter po krugu od N km.

export const OPSTINA_KOORDINATE: Record<string, readonly [number, number]> = {
  "Ada": [45.80, 20.13],
  "Aleksandrovac": [43.45, 21.05],
  "Aleksinac": [43.54, 21.71],
  "Alibunar": [45.08, 20.97],
  "Apatin": [45.67, 18.98],
  "Aranđelovac": [44.31, 20.56],
  "Arilje": [43.75, 20.10],
  "Babušnica": [43.07, 22.41],
  "Bajina Bašta": [43.97, 19.57],
  "Barajevo": [44.60, 20.42],
  "Bač": [45.39, 19.24],
  "Bačka Palanka": [45.25, 19.40],
  "Bačka Topola": [45.81, 19.64],
  "Bela Crkva": [44.90, 21.42],
  "Bela Palanka": [43.22, 22.31],
  "Beograd": [44.81, 20.46],
  "Beočin": [45.19, 19.72],
  "Bečej": [45.62, 20.03],
  "Blace": [43.29, 21.28],
  "Bogatić": [44.84, 19.48],
  "Bojnik": [43.01, 21.72],
  "Boljevac": [43.83, 21.95],
  "Bor": [44.07, 22.10],
  "Bosilegrad": [42.50, 22.47],
  "Brus": [43.38, 21.03],
  "Bujanovac": [42.46, 21.77],
  "Crna Trava": [42.81, 22.30],
  "Despotovac": [44.09, 21.44],
  "Dimitrovgrad": [43.01, 22.78],
  "Doljevac": [43.20, 21.83],
  "Gadžin Han": [43.22, 22.03],
  "Golubac": [44.65, 21.63],
  "Gornji Milanovac": [44.02, 20.46],
  "Grocka": [44.67, 20.72],
  "Inđija": [45.05, 20.08],
  "Irig": [45.10, 19.86],
  "Ivanjica": [43.58, 20.23],
  "Jagodina": [43.98, 21.26],
  "Kanjiža": [46.07, 20.05],
  "Kikinda": [45.83, 20.47],
  "Kladovo": [44.61, 22.61],
  "Knić": [43.92, 20.72],
  "Knjaževac": [43.57, 22.25],
  "Koceljeva": [44.47, 19.82],
  "Kosjerić": [44.00, 19.91],
  "Kovačica": [45.11, 20.62],
  "Kovin": [44.75, 20.98],
  "Kragujevac": [44.01, 20.92],
  "Kraljevo": [43.72, 20.69],
  "Kruševac": [43.58, 21.33],
  "Kula": [45.61, 19.53],
  "Kuršumlija": [43.14, 21.27],
  "Kučevo": [44.48, 21.67],
  "Lajkovac": [44.37, 20.16],
  "Lapovo": [44.18, 21.10],
  "Lazarevac": [44.38, 20.26],
  "Lebane": [42.92, 21.74],
  "Leskovac": [42.99, 21.95],
  "Ljig": [44.22, 20.24],
  "Ljubovija": [44.19, 19.37],
  "Loznica": [44.53, 19.22],
  "Lučani": [43.86, 20.14],
  "Majdanpek": [44.42, 21.94],
  "Mali Iđoš": [45.71, 19.66],
  "Mali Zvornik": [44.40, 19.11],
  "Malo Crniće": [44.56, 21.29],
  "Merošina": [43.28, 21.72],
  "Mionica": [44.25, 20.08],
  "Mladenovac": [44.44, 20.70],
  "Negotin": [44.23, 22.53],
  "Niš": [43.32, 21.90],
  "Nova Crnja": [45.67, 20.60],
  "Nova Varoš": [43.46, 19.81],
  "Novi Bečej": [45.60, 20.13],
  "Novi Kneževac": [46.05, 20.09],
  "Novi Pazar": [43.14, 20.51],
  "Novi Sad": [45.25, 19.85],
  "Obrenovac": [44.66, 20.20],
  "Odžaci": [45.51, 19.26],
  "Opovo": [45.05, 20.43],
  "Osečina": [44.37, 19.60],
  "Pančevo": [44.87, 20.65],
  "Paraćin": [43.86, 21.41],
  "Petrovac na Mlavi": [44.38, 21.42],
  "Pećinci": [44.91, 19.97],
  "Pirot": [43.15, 22.59],
  "Plandište": [45.23, 21.12],
  "Požarevac": [44.62, 21.19],
  "Preševo": [42.31, 21.65],
  "Priboj": [43.58, 19.53],
  "Prijepolje": [43.39, 19.65],
  "Prokuplje": [43.23, 21.59],
  "Rača": [44.23, 20.98],
  "Raška": [43.29, 20.61],
  "Ražanj": [43.67, 21.55],
  "Rekovac": [43.86, 21.09],
  "Ruma": [45.01, 19.82],
  "Senta": [45.93, 20.09],
  "Sečanj": [45.37, 20.77],
  "Sjenica": [43.27, 20.00],
  "Smederevo": [44.66, 20.93],
  "Smederevska Palanka": [44.37, 20.96],
  "Sokobanja": [43.64, 21.87],
  "Sombor": [45.77, 19.11],
  "Sopot": [44.52, 20.58],
  "Srbobran": [45.55, 19.80],
  "Sremska Mitrovica": [44.98, 19.61],
  "Sremski Karlovci": [45.20, 19.93],
  "Stara Pazova": [44.98, 20.16],
  "Subotica": [46.10, 19.67],
  "Surdulica": [42.69, 22.17],
  "Surčin": [44.79, 20.28],
  "Svilajnac": [44.23, 21.20],
  "Svrljig": [43.42, 22.12],
  "Temerin": [45.41, 19.89],
  "Titel": [45.20, 20.30],
  "Topola": [44.25, 20.68],
  "Trstenik": [43.62, 21.00],
  "Ub": [44.46, 20.07],
  "Užice": [43.86, 19.84],
  "Valjevo": [44.27, 19.89],
  "Varvarin": [43.72, 21.36],
  "Velika Plana": [44.33, 21.08],
  "Vladimirci": [44.62, 19.78],
  "Vladičin Han": [42.71, 22.06],
  "Vlasotince": [42.97, 22.13],
  "Vranje": [42.55, 21.90],
  "Vrbas": [45.57, 19.64],
  "Vrnjačka Banja": [43.62, 20.90],
  "Vršac": [45.12, 21.30],
  "Zaječar": [43.90, 22.28],
  "Zrenjanin": [45.38, 20.39],
  "Ćićevac": [43.72, 21.44],
  "Ćuprija": [43.93, 21.37],
  "Čajetina": [43.75, 19.71],
  "Čačak": [43.89, 20.35],
  "Čoka": [45.94, 20.14],
  "Šabac": [44.75, 19.69],
  "Šid": [45.13, 19.23],
  "Žabalj": [45.37, 20.06],
  "Žabari": [44.36, 21.21],
  "Žagubica": [44.20, 21.79],
  "Žitište": [45.49, 20.55],
  "Žitorađa": [43.19, 21.71],
};

export const NASELJE_OPSTINA: Record<string, string> = {
  "Ada": "Ada",
  "Ada Međa": "Ada",
  "Adaševci": "Šid",
  "Adorjan": "Kanjiža",
  "Adrani": "Kraljevo",
  "Akmačići": "Nova Varoš",
  "Aleksa Šantić": "Sombor",
  "Aleksandrovac": "Aleksandrovac",
  "Aleksinac": "Aleksinac",
  "Aleksinački Bujmir": "Aleksinac",
  "Alibunar": "Alibunar",
  "Amajić": "Mali Zvornik",
  "Amerić": "Mladenovac",
  "Apatin": "Apatin",
  "Aradac": "Zrenjanin",
  "Aranđelovac": "Kragujevac",
  "Arilje": "Arilje",
  "Arnajevo": "Barajevo",
  "Azanja": "Smederevska Palanka",
  "Ašanja": "Pećinci",
  "Babušnica": "Babušnica",
  "Bagrdan": "Kragujevac",
  "Bagremovo": "Bačka Topola",
  "Bajina Bašta": "Bajina Bašta",
  "Bajmok": "Subotica",
  "Bajša": "Bačka Topola",
  "Balta Berilovac": "Knjaževac",
  "Banatska Crnja": "Nova Crnja",
  "Banatska Dubica": "Kikinda",
  "Banatska Palanka": "Bela Crkva",
  "Banatska Subotica": "Bela Crkva",
  "Banatska Topola": "Kikinda",
  "Banatski Despotovac": "Žitište",
  "Banatski Karlovac": "Alibunar",
  "Banatsko Aranđelovo": "Novi Kneževac",
  "Banatsko Karađorđevo": "Žitište",
  "Banatsko Novo Selo": "Pančevo",
  "Banja": "Aranđelovac",
  "Banja Koviljača": "Loznica",
  "Banja Pribojska": "Priboj",
  "Banovo Polje": "Bogatić",
  "Barajevo": "Barajevo",
  "Baranda": "Opovo",
  "Barice": "Plandište",
  "Barič": "Obrenovac",
  "Baroševac": "Barajevo",
  "Basara": "Knjaževac",
  "Batinac": "Ćuprija",
  "Batočina": "Kragujevac",
  "Batrovci": "Šid",
  "Batušnica": "Malo Crniće",
  "Bavanište": "Kovin",
  "Bač": "Bač",
  "Bačevci": "Bajina Bašta",
  "Bačina": "Rekovac",
  "Bačinci": "Šid",
  "Bačka Palanka": "Bačka Palanka",
  "Bačka Topola": "Bačka Topola",
  "Bački Breg": "Sombor",
  "Bački Brestovac": "Odžaci",
  "Bački Gračac": "Odžaci",
  "Bački Jarak": "Temerin",
  "Bački Monoštor": "Sombor",
  "Bački Petrovac": "Bač",
  "Bački Sokolac": "Bačka Topola",
  "Bački Vinogradi": "Subotica",
  "Bačko Dobro Polje": "Vrbas",
  "Bačko Dušanovo": "Subotica",
  "Bačko Gradište": "Bečej",
  "Bačko Novo Selo": "Odžaci",
  "Bačko Petrovo Selo": "Bečej",
  "Begaljica": "Grocka",
  "Begeč": "Novi Sad",
  "Bela Crkva": "Bela Crkva",
  "Bela Palanka": "Babušnica",
  "Bela Reka": "Šabac",
  "Bela Voda": "Trstenik",
  "Belegiš": "Stara Pazova",
  "Beljina": "Barajevo",
  "Beloljin": "Prokuplje",
  "Belotić": "Bogatić",
  "Beograd": "Beograd",
  "Beočin": "Beočin",
  "Berkasovo": "Šid",
  "Bezdan": "Sombor",
  "Bečej": "Bečej",
  "Bečevica": "Knić",
  "Bešenovo": "Sremska Mitrovica",
  "Beška": "Inđija",
  "Bikovo": "Subotica",
  "Biljanovac": "Raška",
  "Biljeg": "Aleksinac",
  "Bingula": "Šid",
  "Bioska": "Užice",
  "Bistrica": "Lazarevac",
  "Blace": "Blace",
  "Blagojevići": "Brus",
  "Bogaraš": "Senta",
  "Bogatić": "Bogatić",
  "Bogojevo": "Odžaci",
  "Bogosavac": "Šabac",
  "Bogovađa": "Lajkovac",
  "Bogovina": "Zaječar",
  "Bogutovac": "Raška",
  "Bojanine vode": "Kruševac",
  "Bojnik": "Bojnik",
  "Boka": "Sečanj",
  "Boleč": "Grocka",
  "Boljevac": "Boljevac",
  "Boljevci": "Surčin",
  "Boljkovci": "Kragujevac",
  "Bor": "Bor",
  "Borak": "Rača",
  "Bosilegrad": "Bosilegrad",
  "Botoš": "Zrenjanin",
  "Bovaništa": "Sokobanja",
  "Bođani": "Bač",
  "Bošnjane": "Ljig",
  "Brajkovac": "Ljig",
  "Brangović": "Valjevo",
  "Braničevo": "Požarevac",
  "Brasina": "Mali Zvornik",
  "Bratačić": "Osečina",
  "Brebevnica": "Dimitrovgrad",
  "Bresnica": "Čačak",
  "Brestovac": "Bor",
  "Brestovik": "Grocka",
  "Brestovo": "Bojnik",
  "Brezjak": "Loznica",
  "Brežđe": "Valjevo",
  "Brgule": "Ub",
  "Brodarevo": "Prijepolje",
  "Brodica": "Golubac",
  "Brus": "Brus",
  "Brvenica": "Raška",
  "Brza": "Leskovac",
  "Brza Palanka": "Kladovo",
  "Brđani": "Gornji Milanovac",
  "Budisava": "Novi Sad",
  "Bujanovac": "Vranje",
  "Bukovac": "Novi Sad",
  "Bukovik": "Kragujevac",
  "Bukovče": "Negotin",
  "Bunuševo": "Vranje",
  "Burdimo": "Svrljig",
  "Burovac": "Požarevac",
  "Busur": "Sečanj",
  "Buđanovci": "Ruma",
  "Cerić": "Vladimirci",
  "Crepaja": "Bela Crkva",
  "Crna Bara": "Bogatić",
  "Crna Trava": "Crna Trava",
  "Crvenka": "Kula",
  "Cvetanovac": "Ljig",
  "Debeli Lug": "Majdanpek",
  "Debeljača": "Kovačica",
  "Dedina": "Kruševac",
  "Deliblato": "Kovin",
  "Deronje": "Odžaci",
  "Despotovac": "Despotovac",
  "Despotovo": "Bačka Palanka",
  "Dimitrovgrad": "Dimitrovgrad",
  "Divoš": "Sremska Mitrovica",
  "Divčibare": "Valjevo",
  "Dobanovci": "Surčin",
  "Dobra Voda": "Jagodina",
  "Dobrača": "Arilje",
  "Dobrica": "Alibunar",
  "Dobro Polje": "Leskovac",
  "Dobrovo": "Velika Plana",
  "Dojkinci": "Bela Palanka",
  "Doljevac": "Doljevac",
  "Dolovo": "Pančevo",
  "Donja Badanja": "Loznica",
  "Donja Bela Reka": "Bor",
  "Donja Kamenica": "Knjaževac",
  "Donja Koritnica": "Blace",
  "Donja Krupica": "Varvarin",
  "Donja Lokošnica": "Lebane",
  "Donja Petrušа": "Aleksinac",
  "Donja Rasnica": "Žitorađa",
  "Donje Međurovo": "Niš",
  "Donje Vlase": "Babušnica",
  "Donji Dobrić": "Loznica",
  "Donji Krivodol": "Dimitrovgrad",
  "Donji Milanovac": "Kladovo",
  "Donji Petrovci": "Ruma",
  "Donji Striževac": "Babušnica",
  "Donji Taor": "Valjevo",
  "Donji Tavankut": "Subotica",
  "Doroslovo": "Sombor",
  "Dragan": "Požarevac",
  "Dragijevica": "Osečina",
  "Draginje": "Koceljeva",
  "Dragobraća": "Kragujevac",
  "Dražanj": "Grocka",
  "Draževac": "Obrenovac",
  "Drenovac": "Šabac",
  "Drlupa": "Sopot",
  "Drugovac": "Smederevo",
  "Dublje": "Šabac",
  "Dubona": "Mladenovac",
  "Dupljaja": "Bela Crkva",
  "Dvor": "Vladimirci",
  "Elemir": "Zrenjanin",
  "Erdevik": "Šid",
  "Erčege": "Ivanjica",
  "Ečka": "Zrenjanin",
  "Farkaždun": "Zrenjanin",
  "Feketić": "Mali Iđoš",
  "Fruška Gora": "Surdulica",
  "Futog": "Novi Sad",
  "Gadžin Han": "Gadžin Han",
  "Gaj": "Kovin",
  "Gajdobra": "Bačka Palanka",
  "Gakovo": "Sombor",
  "Gardinovci": "Titel",
  "Gare": "Vranje",
  "Gibarac": "Šid",
  "Globoder": "Kruševac",
  "Glogonj": "Pančevo",
  "Glogovac": "Bogatić",
  "Gložan": "Bač",
  "Gložane": "Smederevska Palanka",
  "Glušci": "Šabac",
  "Gokčanica": "Vrnjačka Banja",
  "Golubac": "Golubac",
  "Golubinci": "Stara Pazova",
  "Goračići": "Užice",
  "Gornja Badanja": "Loznica",
  "Gornja Gorevnica": "Čačak",
  "Gornja Jajina": "Lebane",
  "Gornja Kamenica": "Knjaževac",
  "Gornja Koritnica": "Blace",
  "Gornja Ljuboviđa": "Ljubovija",
  "Gornja Lopušnja": "Merošina",
  "Gornja Rogatica": "Bačka Topola",
  "Gornjane": "Bor",
  "Gornje Međurovo": "Niš",
  "Gornji Barbеš": "Gadžin Han",
  "Gornji Dobrić": "Loznica",
  "Gornji Grad": "Subotica",
  "Gornji Milanovac": "Gornji Milanovac",
  "Gornji Tavankut": "Subotica",
  "Gospođinci": "Žabalj",
  "Goč": "Kraljevo",
  "Goševo": "Novi Pazar",
  "Grabovac": "Obrenovac",
  "Grabovci": "Ruma",
  "Grabovica": "Valjevo",
  "Gradac": "Arilje",
  "Grdelica": "Leskovac",
  "Grgeteg": "Irig",
  "Grgurevci": "Sremska Mitrovica",
  "Grivac": "Knić",
  "Grljan": "Zaječar",
  "Grocka": "Grocka",
  "Gruža": "Kragujevac",
  "Guberevac": "Sopot",
  "Gudurica": "Plandište",
  "Gunaroš": "Bačka Topola",
  "Gučа": "Lučani",
  "Hajdukovo": "Subotica",
  "Halovo": "Zaječar",
  "Hetin": "Žitište",
  "Horgoš": "Subotica",
  "Hrtkovci": "Ruma",
  "Idvor": "Kovačica",
  "Ilandža": "Alibunar",
  "Ilinci": "Šid",
  "Inđija": "Inđija",
  "Irig": "Irig",
  "Ivanjica": "Ivanjica",
  "Izbište": "Vršac",
  "Iđoš": "Kikinda",
  "Jablanica": "Jagodina",
  "Jablanka": "Vršac",
  "Jabuka": "Pančevo",
  "Jabukovac": "Negotin",
  "Jabučje": "Lajkovac",
  "Jagnjilo": "Mladenovac",
  "Jagodina": "Jagodina",
  "Jakovljevo": "Kruševac",
  "Jakovo": "Surčin",
  "Jamena": "Šid",
  "Jankov Most": "Zrenjanin",
  "Janošik": "Alibunar",
  "Jarkovac": "Sečanj",
  "Jasenovo": "Bela Crkva",
  "Jasika": "Kruševac",
  "Jazak": "Irig",
  "Jazovo": "Čoka",
  "Jaša Tomić": "Sečanj",
  "Jelašnica": "Niš",
  "Jermenovci": "Plandište",
  "Jevremovac": "Šabac",
  "Jovanovac": "Kragujevac",
  "Jošanica": "Sokobanja",
  "Jošanička Banja": "Kraljevo",
  "Junkovac": "Lazarevac",
  "Kablar": "Čačak",
  "Kajtasovo": "Bela Crkva",
  "Kalenić": "Ub",
  "Kaluđerica": "Grocka",
  "Kaluđerske Bare": "Priboj",
  "Kamenovo": "Petrovac na Mlavi",
  "Kanjiža": "Kanjiža",
  "Karajukića Bunari": "Sjenica",
  "Karaula": "Novi Pazar",
  "Karavukovo": "Sombor",
  "Karađorđevo": "Bačka Topola",
  "Katun": "Aleksinac",
  "Kavilo": "Bačka Topola",
  "Kać": "Novi Sad",
  "Kačarevo": "Pančevo",
  "Kelebija": "Subotica",
  "Kevi": "Senta",
  "Kikinda": "Kanjiža",
  "Kisač": "Novi Sad",
  "Kladovo": "Kladovo",
  "Klačevica": "Paraćin",
  "Klenak": "Ruma",
  "Klenovnik": "Požarevac",
  "Klinci": "Valjevo",
  "Klisura": "Doljevac",
  "Kličevac": "Požarevac",
  "Kljajićevo": "Sombor",
  "Knić": "Knić",
  "Knićanin": "Zrenjanin",
  "Knjaževac": "Knjaževac",
  "Koceljeva": "Šabac",
  "Kokin Brod": "Nova Varoš",
  "Kolari": "Smederevo",
  "Kolut": "Sombor",
  "Kom": "Niš",
  "Konarevo": "Kragujevac",
  "Konjević": "Gornji Milanovac",
  "Konjevići": "Čačak",
  "Konjska": "Ivanjica",
  "Kopaonik": "Raška",
  "Kopljare": "Aranđelovac",
  "Koprivštica": "Pirot",
  "Koraćica": "Mladenovac",
  "Korbeul": "Vranje",
  "Kosančić": "Vrbas",
  "Kosjerić": "Kosjerić",
  "Kostolac": "Požarevac",
  "Kotešica": "Valjevo",
  "Kotraža": "Lučani",
  "Kovačica": "Kovačica",
  "Kovilj": "Novi Sad",
  "Koviljača": "Loznica",
  "Kovin": "Kovin",
  "Kragujevac": "Kragujevac",
  "Kraljevci": "Ruma",
  "Kraljevo": "Kraljevo",
  "Kremna": "Čajetina",
  "Krivaja": "Bačka Topola",
  "Krivelj": "Bor",
  "Krnjevo": "Velika Plana",
  "Krtinska": "Obrenovac",
  "Krupac": "Pirot",
  "Krušedol Prnjavor": "Irig",
  "Kruševac": "Kruševac",
  "Kruševica": "Lazarevac",
  "Kruščica": "Bela Crkva",
  "Kruščić": "Kula",
  "Krčagovo": "Užice",
  "Krčedin": "Inđija",
  "Kucura": "Srbobran",
  "Kukljin": "Kruševac",
  "Kukujevci": "Šid",
  "Kula": "Kula",
  "Kulpin": "Bač",
  "Kumane": "Novi Bečej",
  "Kupinovo": "Pećinci",
  "Kupusina": "Apatin",
  "Kuršumlija": "Brus",
  "Kusadak": "Smederevska Palanka",
  "Kusić": "Bela Crkva",
  "Kučevo": "Majdanpek",
  "Kušiljevo": "Svilajnac",
  "Lajkovac": "Lajkovac",
  "Lalaš": "Odžaci",
  "Lalić": "Odžaci",
  "Lapotince": "Leskovac",
  "Lapovo": "Lapovo",
  "Lazarevac": "Lazarevac",
  "Lazarevo": "Zrenjanin",
  "Laćarak": "Sremska Mitrovica",
  "Laćinak": "Kruševac",
  "Lebane": "Lebane",
  "Ledinci": "Novi Sad",
  "Lelić": "Valjevo",
  "Lenovac": "Zaječar",
  "Leskovac": "Zaječar",
  "Lestane": "Grocka",
  "Levosoje": "Bujanovac",
  "Lipar": "Kula",
  "Lipe": "Smederevo",
  "Lipnica": "Loznica",
  "Lipolist": "Šabac",
  "Lipova": "Vrnjačka Banja",
  "Lipovica": "Kruševac",
  "Ljig": "Ljig",
  "Ljuba": "Šid",
  "Ljubovija": "Ljubovija",
  "Ljutovo": "Subotica",
  "Lock": "Titel",
  "Locve": "Alibunar",
  "Lok": "Žabalj",
  "Lovćenac": "Mali Iđoš",
  "Lozan": "Svrljig",
  "Loznica": "Loznica",
  "Lozovik": "Trstenik",
  "Lug": "Beočin",
  "Lukavica": "Lazarevac",
  "Lukićevo": "Zrenjanin",
  "Lukovo": "Boljevac",
  "Lukovska Banja": "Kuršumlija",
  "Lunjevac": "Smederevo",
  "Lučane": "Rekovac",
  "Lučani": "Čačak",
  "Lučica": "Požarevac",
  "Maglić": "Bač",
  "Majdanpek": "Majdanpek",
  "Majur": "Šabac",
  "Mala Bosna": "Subotica",
  "Mala Ivanča": "Sopot",
  "Mala Remeta": "Irig",
  "Male Pijace": "Kanjiža",
  "Mali Bajmok": "Subotica",
  "Mali Beograd": "Bačka Topola",
  "Mali Izvor": "Boljevac",
  "Mali Iđoš": "Bačka Topola",
  "Mali Zvornik": "Mali Zvornik",
  "Mali Žam": "Vršac",
  "Malo Crniće": "Malo Crniće",
  "Malča": "Niš",
  "Manasija": "Petrovac na Mlavi",
  "Manđelos": "Sremska Mitrovica",
  "Maradik": "Inđija",
  "Markovac": "Mladenovac",
  "Markovićevo": "Plandište",
  "Martinci": "Sremska Mitrovica",
  "Martonoš": "Kanjiža",
  "Masurče": "Vladičin Han",
  "Mataruška Banja": "Kraljevo",
  "Mačkovac": "Kruševac",
  "Mačvanska Mitrovica": "Sremska Mitrovica",
  "Medoševac": "Lazarevac",
  "Medveđa": "Despotovac",
  "Melenci": "Zrenjanin",
  "Meljak": "Barajevo",
  "Merdare": "Kuršumlija",
  "Merošina": "Merošina",
  "Merćez": "Prokuplje",
  "Mesić": "Vršac",
  "Metković": "Šabac",
  "Metovnica": "Zaječar",
  "Mezgraja": "Niš",
  "Mečkovac": "Kosjerić",
  "Međa": "Žitište",
  "Međulužje": "Mladenovac",
  "Mihajlovac": "Smederevo",
  "Mihajlovo": "Zrenjanin",
  "Mijatovac": "Ćuprija",
  "Milatkovići": "Kraljevo",
  "Mileševo": "Bečej",
  "Miliva": "Despotovac",
  "Milutovac": "Trstenik",
  "Miokus": "Šabac",
  "Mionica": "Mionica",
  "Mirosaljci": "Lazarevac",
  "Miroč": "Kladovo",
  "Mislođin": "Obrenovac",
  "Mićunovo": "Bačka Topola",
  "Miševića Mahala": "Jagodina",
  "Mišićevo": "Subotica",
  "Mladenovac": "Mladenovac",
  "Mladenovo": "Bačka Palanka",
  "Mol": "Ada",
  "Molovin": "Šid",
  "Moravac": "Aleksinac",
  "Morović": "Šid",
  "Mosna": "Majdanpek",
  "Mozgovo": "Aleksinac",
  "Mošorin": "Titel",
  "Mramorak": "Kovin",
  "Mrčajevci": "Čačak",
  "Mršane": "Prokuplje",
  "Muhovac": "Bujanovac",
  "Mur": "Raška",
  "Nadalj": "Srbobran",
  "Nakovo": "Kikinda",
  "Nakučani": "Šabac",
  "Negbina": "Nova Varoš",
  "Negotin": "Negotin",
  "Nemenikuće": "Sopot",
  "Neradin": "Irig",
  "Neštin": "Bačka Palanka",
  "Nikinci": "Ruma",
  "Nikolinci": "Alibunar",
  "Niš": "Niš",
  "Niševac": "Pirot",
  "Nišević": "Kruševac",
  "Nišor": "Niš",
  "Njegoševo": "Bačka Topola",
  "Nova Crnja": "Nova Crnja",
  "Nova Crvenka": "Kula",
  "Nova Gajdobra": "Bačka Palanka",
  "Nova Pazova": "Stara Pazova",
  "Nova Varoš": "Nova Varoš",
  "Novi Banovci": "Stara Pazova",
  "Novi Beograd": "Beograd",
  "Novi Bečej": "Novi Bečej",
  "Novi Kneževac": "Novi Kneževac",
  "Novi Kozarci": "Kikinda",
  "Novi Pazar": "Novi Pazar",
  "Novi Sad": "Novi Sad",
  "Novi Slankamen": "Inđija",
  "Novi Žednik": "Subotica",
  "Novo Miloševo": "Novi Bečej",
  "Novo Orahovo": "Bačka Topola",
  "Noćaj": "Sremska Mitrovica",
  "Nošpaljevac": "Leskovac",
  "Obornjača": "Ada",
  "Obrenovac": "Obrenovac",
  "Obrež": "Pećinci",
  "Obrovac": "Bačka Palanka",
  "Odžaci": "Odžaci",
  "Omoljica": "Pančevo",
  "Oplenac": "Topola",
  "Opovo": "Opovo",
  "Orašac": "Šabac",
  "Orešac": "Vršac",
  "Orljane": "Doljevac",
  "Orom": "Kanjiža",
  "Osečina": "Osečina",
  "Oskoruša": "Bajina Bašta",
  "Ostojićevo": "Čoka",
  "Oštrelj": "Bor",
  "Padej": "Kanjiža",
  "Padina": "Kovačica",
  "Palilula": "Beograd",
  "Palić": "Subotica",
  "Pambukovica": "Valjevo",
  "Panonija": "Bačka Topola",
  "Pančevo": "Pančevo",
  "Parage": "Bač",
  "Paraćin": "Paraćin",
  "Parcani": "Sopot",
  "Partoš": "Vršac",
  "Parunovac": "Kruševac",
  "Pavliš": "Vršac",
  "Pačir": "Bačka Topola",
  "Pepeljevac": "Kruševac",
  "Perlez": "Zrenjanin",
  "Perućac": "Bajina Bašta",
  "Petka": "Lazarevac",
  "Petlovača": "Šabac",
  "Petnica": "Loznica",
  "Petrovac na Mlavi": "Petrovac na Mlavi",
  "Petrovčić": "Surčin",
  "Pećinci": "Pećinci",
  "Pilica": "Loznica",
  "Pirot": "Pirot",
  "Pivnice": "Bačka Palanka",
  "Plandište": "Plandište",
  "Planinica": "Zaječar",
  "Platičevo": "Ruma",
  "Plavna": "Bač",
  "Ploča": "Prokuplje",
  "Pločnik": "Prokuplje",
  "Pobeda": "Bačka Topola",
  "Popinci": "Inđija",
  "Popučke": "Valjevo",
  "Postenje": "Ljubovija",
  "Pot": "Užice",
  "Potočac": "Paraćin",
  "Potporanj": "Vršac",
  "Požarevac": "Požarevac",
  "Prahovo": "Negotin",
  "Predejane": "Leskovac",
  "Preljina": "Čačak",
  "Preševo": "Preševo",
  "Priboj": "Priboj",
  "Prigrevica": "Apatin",
  "Prijepolje": "Prijepolje",
  "Prilike": "Ivanjica",
  "Prislonica": "Čačak",
  "Privina Glava": "Šid",
  "Pričević": "Valjevo",
  "Prnjavor": "Šabac",
  "Progar": "Surčin",
  "Progorelica": "Smederevska Palanka",
  "Progoreoci": "Aranđelovac",
  "Prokuplje": "Prokuplje",
  "Prosek": "Niš",
  "Prćilovica": "Jagodina",
  "Pudarci": "Grocka",
  "Putinci": "Stara Pazova",
  "Rabe": "Novi Kneževac",
  "Rabrovac": "Mladenovac",
  "Rabrovo": "Kučevo",
  "Radičević": "Bečej",
  "Radoinja": "Nova Varoš",
  "Radujevac": "Negotin",
  "Rakovac": "Beočin",
  "Rakovica": "Beograd",
  "Ram": "Golubac",
  "Rasina": "Kruševac",
  "Rasno": "Sjenica",
  "Rastina": "Sombor",
  "Ratina": "Kraljevo",
  "Ratkovo": "Odžaci",
  "Ravni Topolovac": "Žitište",
  "Ravniška": "Petrovac na Mlavi",
  "Ravnje": "Sremska Mitrovica",
  "Ravno Selo": "Vrbas",
  "Rača": "Bajina Bašta",
  "Raška": "Raška",
  "Ražanj": "Ražanj",
  "Rekovac": "Rekovac",
  "Resavica": "Despotovac",
  "Resnik": "Kragujevac",
  "Rgotina": "Boljevac",
  "Ribari": "Šabac",
  "Ribnica": "Kraljevo",
  "Ritopek": "Grocka",
  "Rivica": "Irig",
  "Riđica": "Sombor",
  "Roanda": "Svilajnac",
  "Rogača": "Sopot",
  "Rogljevo": "Negotin",
  "Roćevci": "Ćićevac",
  "Rožanci": "Barajevo",
  "Rudan": "Kraljevo",
  "Rudnik": "Gornji Milanovac",
  "Rudovci": "Lazarevac",
  "Rujišta": "Aleksandrovac",
  "Ruma": "Ruma",
  "Rumenka": "Novi Sad",
  "Ruski Krstur": "Kula",
  "Rusko Selo": "Kikinda",
  "Ručić": "Valjevo",
  "Rvati": "Obrenovac",
  "Sajan": "Kikinda",
  "Sakule": "Zrenjanin",
  "Salaš Noćajski": "Bogatić",
  "Salašinci": "Sremska Mitrovica",
  "Sanad": "Kikinda",
  "Santrač": "Kikinda",
  "Saraorci": "Grocka",
  "Savino Selo": "Vrbas",
  "Savski venac": "Beograd",
  "Selenča": "Bač",
  "Seleuš": "Alibunar",
  "Senaja": "Mladenovac",
  "Senta": "Senta",
  "Sevojno": "Užice",
  "Seča Reka": "Kosjerić",
  "Sečanj": "Sečanj",
  "Sibnica": "Barajevo",
  "Sige": "Žagubica",
  "Sijarinska Banja": "Leskovac",
  "Sikirica": "Paraćin",
  "Silbaš": "Bačka Palanka",
  "Sirig": "Temerin",
  "Sirogojno": "Čajetina",
  "Sivac": "Kula",
  "Sjenica": "Sjenica",
  "Skela": "Obrenovac",
  "Skiropoj": "Šabac",
  "Skradnik": "Vladimirci",
  "Slatina": "Sopot",
  "Smederevo": "Smederevo",
  "Smederevska Palanka": "Smederevska Palanka",
  "Smokovac": "Ivanjica",
  "Smoljinac": "Malo Crniće",
  "Sokobanja": "Sokobanja",
  "Sokolovo": "Lazarevac",
  "Sombor": "Sombor",
  "Sonta": "Apatin",
  "Sopot": "Sopot",
  "Sot": "Šid",
  "Sovljak": "Bogatić",
  "Srbobran": "Srbobran",
  "Sremska Mitrovica": "Stara Pazova",
  "Sremski Karlovci": "Sremski Karlovci",
  "Srnje": "Kruševac",
  "Srpska Crnja": "Nova Crnja",
  "Srpski Itebej": "Žitište",
  "Srpski Krstur": "Novi Kneževac",
  "Srpski Miletić": "Odžaci",
  "Stajićevo": "Zrenjanin",
  "Stajkovce": "Vlasotince",
  "Staničenje": "Vranje",
  "Stanišić": "Sombor",
  "Stapar": "Sombor",
  "Stara Banja": "Kuršumlija",
  "Stara Moravica": "Bačka Topola",
  "Stara Pazova": "Stara Pazova",
  "Stari grad": "Beograd",
  "Stari Lec": "Plandište",
  "Stari Slankamen": "Inđija",
  "Stari Žednik": "Subotica",
  "Starčevo": "Pančevo",
  "Stejanovci": "Ruma",
  "Stenjevac": "Despotovac",
  "Stepanje": "Valjevo",
  "Stepanovićevo": "Novi Sad",
  "Stepojevac": "Lazarevac",
  "Sterijino": "Ada",
  "Strigulja": "Ćuprija",
  "Strojinci": "Kruševac",
  "Strojkovce": "Leskovac",
  "Struganik": "Mionica",
  "Stubline": "Obrenovac",
  "Subotica": "Subotica",
  "Subotinac": "Aleksinac",
  "Surdulica": "Surdulica",
  "Surčin": "Surčin",
  "Susek": "Beočin",
  "Sutjeska": "Sečanj",
  "Suva Morava": "Leskovac",
  "Svetićevo": "Bačka Topola",
  "Svetozar Miletić": "Sombor",
  "Svilajnac": "Svilajnac",
  "Svilojevo": "Apatin",
  "Sviloš": "Beočin",
  "Svrljig": "Svrljig",
  "Svrljiški Timok": "Knjaževac",
  "Tabakovac": "Zaječar",
  "Tabanović": "Šabac",
  "Tabanovići": "Šabac",
  "Takovo": "Valjevo",
  "Tanda": "Bor",
  "Tara": "Surdulica",
  "Taraš": "Zrenjanin",
  "Tavankut": "Subotica",
  "Telečka": "Sombor",
  "Temerin": "Temerin",
  "Titel": "Titel",
  "Tomislavci": "Bačka Topola",
  "Topla": "Bor",
  "Toplica": "Mionica",
  "Topola": "Topola",
  "Toponica": "Knjaževac",
  "Torak": "Žitište",
  "Torda": "Kanjiža",
  "Tornjoš": "Senta",
  "Tovariševo": "Sombor",
  "Trbušica": "Čačak",
  "Trešnje": "Aranđelovac",
  "Trešnjevac": "Kanjiža",
  "Trešnjevica": "Loznica",
  "Trnava": "Novi Pazar",
  "Trnavci": "Čačak",
  "Trnovo": "Požarevac",
  "Trstenik": "Trstenik",
  "Trupale": "Niš",
  "Tršić": "Loznica",
  "Turica": "Užice",
  "Turija": "Srbobran",
  "Turkovce": "Leskovac",
  "Tutin": "Novi Pazar",
  "Ub": "Ub",
  "Ugrinovci": "Surčin",
  "Urovci": "Obrenovac",
  "Usje": "Golubac",
  "Utrine": "Ada",
  "Uzdin": "Kovačica",
  "Uzveće": "Šabac",
  "Ušće": "Kraljevo",
  "Užice": "Užice",
  "Vajska": "Bač",
  "Valakonje": "Boljevac",
  "Valjevo": "Valjevo",
  "Varvarin": "Kruševac",
  "Vašica": "Šid",
  "Velebit": "Kanjiža",
  "Velika Drenova": "Kruševac",
  "Velika Plana": "Velika Plana",
  "Veliki Izvor": "Zaječar",
  "Veliko Središte": "Plandište",
  "Venčane": "Aranđelovac",
  "Verbica": "Zrenjanin",
  "Verušić": "Subotica",
  "Veternik": "Novi Sad",
  "Vilje": "Vlasotince",
  "Vilovo": "Titel",
  "Vinci": "Golubac",
  "Vinoča": "Koceljeva",
  "Vinča": "Grocka",
  "Virine": "Despotovac",
  "Vizić": "Bačka Palanka",
  "Viševac": "Rača",
  "Višnjevac": "Subotica",
  "Vladimirci": "Vladimirci",
  "Vladimirovo": "Alibunar",
  "Vladičin Han": "Vladičin Han",
  "Vlajkovac": "Vršac",
  "Vlasina": "Surdulica",
  "Vlasina Rid": "Surdulica",
  "Vlasotince": "Vlasotince",
  "Vlaška": "Mladenovac",
  "Vojvoda Bojović": "Vršac",
  "Vojvoda Stepa": "Nova Crnja",
  "Voluja": "Žagubica",
  "Voždovac": "Beograd",
  "Vranić": "Barajevo",
  "Vranje": "Vranje",
  "Vranješević": "Novi Bečej",
  "Vračar": "Beograd",
  "Vrbas": "Vrbas",
  "Vrbovac": "Vranje",
  "Vrdnik": "Irig",
  "Vreoci": "Lazarevac",
  "Vrnjačka Banja": "Vrnjačka Banja",
  "Vršac": "Vršac",
  "Vučje": "Leskovac",
  "Zaječar": "Negotin",
  "Zasavica": "Sremska Mitrovica",
  "Zemun": "Beograd",
  "Zlatar": "Nova Varoš",
  "Zlatibor": "Čajetina",
  "Zlot": "Bor",
  "Zmajevo": "Vrbas",
  "Zminjak": "Šabac",
  "Zobnatica": "Bačka Topola",
  "Zrenjanin": "Zrenjanin",
  "Zvezdara": "Beograd",
  "Ćićevac": "Ćićevac",
  "Ćuprija": "Ćuprija",
  "Čajetina": "Čajetina",
  "Čalma": "Sremska Mitrovica",
  "Čantavir": "Subotica",
  "Čačak": "Čajetina",
  "Čelarevo": "Bačka Palanka",
  "Čenej": "Novi Sad",
  "Čenta": "Zrenjanin",
  "Čoka": "Čoka",
  "Čonoplja": "Sombor",
  "Čortanovci": "Inđija",
  "Čukarica": "Beograd",
  "Čukurovac": "Aleksinac",
  "Čurug": "Žabalj",
  "Đolovo": "Kuršumlija",
  "Đunis": "Ćićevac",
  "Đurđevo": "Žabalj",
  "Đurđin": "Subotica",
  "Šabac": "Šabac",
  "Šajkaš": "Titel",
  "Šalinac": "Smederevo",
  "Šanac": "Jagodina",
  "Šarbane": "Lajkovac",
  "Šarbanovac": "Bor",
  "Šarkamen": "Negotin",
  "Šatrinci": "Irig",
  "Šavac": "Paraćin",
  "Šid": "Šid",
  "Šiljakovac": "Barajevo",
  "Šimanovci": "Pećinci",
  "Šljivar": "Zaječar",
  "Šopić": "Lazarevac",
  "Štitar": "Bogatić",
  "Štrbac": "Kladovo",
  "Šugrine": "Pirot",
  "Šumarak": "Kovin",
  "Šumarice": "Kragujevac",
  "Šume": "Ivanjica",
  "Šupljak": "Subotica",
  "Šurovina": "Aleksinac",
  "Žabalj": "Žabalj",
  "Žabari": "Žabari",
  "Žagubica": "Žagubica",
  "Žarkovac": "Ruma",
  "Žitište": "Žitište",
  "Žitorađa": "Žitorađa",
  "Župa": "Aleksandrovac",
};

